name: frontend
description: "A budget app for the garbanzo family"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

flutter:
  uses-material-design: true

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl: ^0.18.1 # For date formatting
  fl_chart: ^0.63.0 # For charts
  uuid: ^4.1.0 # For unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
